### ISSUE TITLE
Add extra validations for Gobstones Kids tests

### ISSUE THREAD

**Issue by flbulgarelli** [mumuki/mumuki-bibliotheca-api#102]
When using blocks in kids layout, we are assuming a lot of simplifications on the test spec:

* There are no `subject`s
* There is only one test scenario - @see https://github.com/mumuki/mumuki-bibliotheca-api/pull/101/files
* `check_head_position` is always fails - right? @NadiaFinzi @luchotc 
* There is no title - actually it won't be displayed

We should add validation to `biblitoheca` - and maybe to the runner itself

**Comment by flbulgarelli** [comment]
> Yep, in kids it should always be false, but only for a pedagogic reason. There is no limitation in the runner.

But will it be any way of displaying it to the user if we remove the results popup https://github.com/mumuki/mumuki-laboratory/issues/1001?

**Comment by flbulgarelli** [comment]
> There CAN'T be any subjects

Can't the user enter them?

**Comment by luchotc** [comment]
To sum up:

In bibliotheca:
Prevent user from entering subject, check_head_position, title and only one final and initial_board

I don't think any of these are worth validating in the runner. What do you think @flbulgarelli ?

**Comment by flbulgarelli** [comment]
We should validate them here. 

However, validating the subject in the runner is a plus which improves robustness.
