### ISSUE TITLE
El código extra de la guía no se guarda bien

### ISSUE THREAD

**Issue by faloi** [mumuki/mumuki-bibliotheca-api#131]
Me está pasando con esta guía: http://bibliotheca.mumuki.io/#/guides/mumukiproject/mumuki-guia-ruby-polimorfismo

Yo tenía un código extra, que ahora quiero borrar y no puedo. La secuencia que más o menos logré sistematizar es esta:

1. Voy a la vista de guía, borro el código extra y guardo.
2. Recargo laboratorio, el código extra no está.
3. Miro en GitHub, no hay nuevos commits, el código extra sigue estando ahí. Si abro otra pestaña con bibliotheca, el código también aparece ahí.
4. Modifico algo de algún ejercicio, guardo.
5. El código extra vuelve a aparecer en laboratorio.

**Comment by flbulgarelli** [comment]
I think this was happening because the corresponding field was not being persisted and/or exported to Github - causing race conditions and self-destroying the data after the webhook. 

@rodri042 could you check this field is actually being persisted - in `mumuki-domain` and exported - in `bibliotheca-api`?

**Comment by rodri042** [comment]
This is both exporting and persisting well. Closing the issue...

![screenshot1](https://user-images.githubusercontent.com/1631752/49612223-c3bfed00-f982-11e8-977f-2bb9d8ee5d5c.png)
![screenshot2](https://user-images.githubusercontent.com/1631752/49612227-c6224700-f982-11e8-90c9-1f1da3739b7c.png)
![screenshot3](https://user-images.githubusercontent.com/1631752/49612229-c884a100-f982-11e8-97ab-d89d32b63188.png)
![screenshot6](https://user-images.githubusercontent.com/1631752/49612232-cae6fb00-f982-11e8-9aef-6542f7aacf79.png)
