### ISSUE TITLE
Guide extra code is not removed from GitHub

### ISSUE THREAD

**Issue by faloi** [mumuki/mumuki-bibliotheca-api#132]

**Comment by rodri042** [comment]
This is a very old issue.

I've been testing it and `mumukit-sync` [correctly deleted the `extra.gbs` file](https://github.com/rodri042/mumuki-guia-gobstones-aaa-prueba/commit/0aeac9e56f14d1c4e4eebd7870fbfe13b5fb37bb) when I removed it from Bibliotheca. Closing...
