### ISSUE TITLE
Add exercises count to guides endpoint

### ISSUE THREAD

**Issue by faloi** [mumuki/mumuki-bibliotheca-api#67]

**Comment by flbulgarelli** [comment]
Why?

**Comment by flbulgarelli** [comment]
Moreover, we are deprecating APIs for internal usage in favor of queue consumption

**Comment by flbulgarelli** [comment]
I assume this is the root cause: https://github.com/mumuki/mumuki-platform/issues/184. So I am closing this issue as its duplicate.
