### ISSUE TITLE
Both Import api and save guide should  both downcase slugs

### ISSUE THREAD

**Issue by flbulgarelli** [mumuki/mumuki-bibliotheca-api#86]
Slugs should be always in downcase.

**Comment by luchotc** [comment]
This should be done for create and import endpoints. Update should remain the same

**Comment by flbulgarelli** [comment]
This applies also to fork api.

**Comment by flbulgarelli** [comment]
I have extracted a `normalize` method here: https://github.com/mumuki/mumukit-auth/pull/31. It should make this task easier.

**Comment by flbulgarelli** [comment]
Another good approach for this may be just normalizing slugs when creating new guides in `domain`
